version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "master_password"
      MYSQL_DATABASE: "BookingDb"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

